# this is the docker-compose version
version: '3.0'

# file version BEA_VERSION_TIMESTAMP

networks:
    # network for this compose stack
    stdmw_network_<ENVIRON>:
        driver: bridge
#SUBNET        ipam:
#SUBNET            config:
#SUBNET            - subnet: <SUBNET>
services:
    stdmw_service:
        networks:
            - stdmw_network_<ENVIRON>
        # restart this container if it crashes
        restart: always
        build:
            # build from directory in context and Dockerfile
            context: .
            dockerfile: Dockerfile
        container_name: stdmw_cont_<ENVIRON>
        image: <IMAGEURL>
        volumes:
            # outside access for data files outside:inside
            - <CONFIGPATH>:/SMW/MW_CACHE:ro
            - <ZIPTMPPATH>:/SMW/MW_ZIP
            - <LOGPATH>:/opt/tomcat/logs
            # read-only file to set time to same in image as on server
            - /etc/localtime:/etc/localtime:ro
        ports:
            # (outside)host port:container port(inside) for Tomcat
            # outside/host port is only set here (other docker compose have ports in more than one place)
            - "<OUTSIDE_PORT>:8080"
        tty: true

